server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:KapilBommanchi/config-server-properties.git
          default-label: main
          ignoreLocalSshSettings: true
          privateKey: |
            -----PRIVATE KEY-----
            <place private key here>
            -----PRIVATE KEY-----
    bus:
      enabled: true
      id: my-config-server
    stream:
      kafka:
        binder:
          zkNodes: localhost:2181
          brokers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"